/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author TAMU
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuFileClearWindow = new javax.swing.JMenuItem();
        MenuFileClose = new javax.swing.JMenuItem();
        MenuLihatLaporan = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuEditTableAngsuran = new javax.swing.JMenuItem();
        MenuEditTableBarang = new javax.swing.JMenuItem();
        MenuEditTableCustomer = new javax.swing.JMenuItem();
        MenuEditTableGadai = new javax.swing.JMenuItem();
        MenuEditTableJenisBarang = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pegadaian V.1.0");
        setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        MenuFileClearWindow.setText("Clear Window");
        MenuFileClearWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFileClearWindowActionPerformed(evt);
            }
        });
        jMenu1.add(MenuFileClearWindow);

        MenuFileClose.setText("Close");
        MenuFileClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuFileCloseMouseClicked(evt);
            }
        });
        MenuFileClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFileCloseActionPerformed(evt);
            }
        });
        jMenu1.add(MenuFileClose);

        MenuLihatLaporan.setText("Lihat Laporan");
        MenuLihatLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLihatLaporanActionPerformed(evt);
            }
        });
        jMenu1.add(MenuLihatLaporan);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit Tabel");

        MenuEditTableAngsuran.setText("Angsuran Gadai");
        MenuEditTableAngsuran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuEditTableAngsuranMouseClicked(evt);
            }
        });
        MenuEditTableAngsuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEditTableAngsuranActionPerformed(evt);
            }
        });
        jMenu2.add(MenuEditTableAngsuran);

        MenuEditTableBarang.setText("Barang Gadai");
        MenuEditTableBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEditTableBarangActionPerformed(evt);
            }
        });
        jMenu2.add(MenuEditTableBarang);

        MenuEditTableCustomer.setText("Customer");
        MenuEditTableCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEditTableCustomerActionPerformed(evt);
            }
        });
        jMenu2.add(MenuEditTableCustomer);

        MenuEditTableGadai.setText("Gadai");
        MenuEditTableGadai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEditTableGadaiActionPerformed(evt);
            }
        });
        jMenu2.add(MenuEditTableGadai);

        MenuEditTableJenisBarang.setText("Jenis Barang");
        MenuEditTableJenisBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEditTableJenisBarangActionPerformed(evt);
            }
        });
        jMenu2.add(MenuEditTableJenisBarang);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuFileClearWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFileClearWindowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuFileClearWindowActionPerformed

    private void MenuFileCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuFileCloseMouseClicked
        
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuFileCloseMouseClicked

    private void MenuEditTableAngsuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEditTableAngsuranActionPerformed
        ViewAngsuranGadai a = new ViewAngsuranGadai();
        a.show();
        DesktopPane.add(a);
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuEditTableAngsuranActionPerformed

    private void MenuEditTableAngsuranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuEditTableAngsuranMouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_MenuEditTableAngsuranMouseClicked

    private void MenuFileCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFileCloseActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_MenuFileCloseActionPerformed

    private void MenuEditTableBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEditTableBarangActionPerformed
        ViewBarangGadai b = new ViewBarangGadai();
        b.show();
        DesktopPane.add(b);
// TODO add your handling code here:
    }//GEN-LAST:event_MenuEditTableBarangActionPerformed

    private void MenuEditTableCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEditTableCustomerActionPerformed
        ViewCustomer c = new ViewCustomer();
        c.show();
        DesktopPane.add(c);
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuEditTableCustomerActionPerformed

    private void MenuEditTableGadaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEditTableGadaiActionPerformed
        ViewGadai d = new ViewGadai();
        d.show();
        DesktopPane.add(d);
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuEditTableGadaiActionPerformed

    private void MenuEditTableJenisBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEditTableJenisBarangActionPerformed
        ViewJenisBarang e = new ViewJenisBarang();
        e.show();
        DesktopPane.add(e);
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuEditTableJenisBarangActionPerformed

    private void MenuLihatLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLihatLaporanActionPerformed
        // TODO add your handling code here:
        Report r = new Report();
        try {
                String path = "Pegadaian/Pegadaian.jasper";
                String driver="oracle.jdbc.OracleDriver";
                String konek="jdbc:oracle:thin:@localhost:1521:XE";
                String user="system";
                String password="12345";
                HashMap parameter = new HashMap();
                Class.forName(driver);
                Connection conn = DriverManager.getConnection(konek,user,password);
                File reportFile=new File(path);
                InputStream jReport = this.getClass().getClassLoader().getResourceAsStream(reportFile.getPath());
//                JasperReport jReport = (JasperReport) JRLoader.loadObject(reportFile.getPath());
                JasperPrint jPrint = JasperFillManager.fillReport(jReport, parameter, conn);
                JasperViewer.viewReport(jPrint, true);
                JasperViewer.setDefaultLookAndFeelDecorated(true);
                JasperViewer viewer = new JasperViewer(jPrint);
                r.add(viewer);
                r.setVisible(true);
                DesktopPane.add(viewer);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Laporan Tidak Dapat Dicetak!\n" + e.getMessage()
                ,"Cetak Laporan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MenuLihatLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Thread.sleep(2155);
                } catch (Exception e) {
                }
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenuItem MenuEditTableAngsuran;
    private javax.swing.JMenuItem MenuEditTableBarang;
    private javax.swing.JMenuItem MenuEditTableCustomer;
    private javax.swing.JMenuItem MenuEditTableGadai;
    private javax.swing.JMenuItem MenuEditTableJenisBarang;
    private javax.swing.JMenuItem MenuFileClearWindow;
    private javax.swing.JMenuItem MenuFileClose;
    private javax.swing.JMenuItem MenuLihatLaporan;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
